ClassManager/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
]

main/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "main"
urlpatterns = [
    path('', views.home, name='home'),
    path('search', views.search, name='search'),
    path('settings', views.settings, name='settings'),

    path('login_view', views.login_view, name='login_view'),
    path('register_view', views.register_view, name='register_view'),
    path('logout_view', views.logout_view, name='logout_view'),

    path('delete/<int:pk>/<str:option>', views.delete, name='delete'),

    path('building/<int:pk>', views.building, name='building'),
    path('class_view/<str:name>', views.class_view, name='class'),

    path('create_teacher/<str:name>', views.create_teacher, name='create_teacher'),
    path('all_teachers/', views.all_teachers, name='all_teachers'),
    path('teacher/<int:pk>', views.teacher, name='teacher'),

    path('create_student/', views.create_student, name='create_student'),
    path('all_students/', views.all_students, name='all_students'),
    path('student/<int:pk>', views.student, name='student'),

    path('nextYear/', views.nextYear, name='nextYear'),
    path('train/<int:pk>', views.train, name='train'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class School(AbstractUser):
    name = models.CharField(max_length=30, default="My New School")
    year = models.IntegerField(default=1)
    actionTokens = models.IntegerField(default=3)
    money = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(1000000000)], blank=True, null=True, default=500000)
    tuition = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100000)], blank=True, null=True, default=50000)

    def advanceYear(self, costs):
        self.year+=1
        # reset user action tokens every year
        self.actionTokens = 3
        self.payCosts(costs)
        self.save()

    def payCosts(self, cost):
        self.money+=cost
        self.save()

    def checkTokens(self):
        return self.actionTokens
    
    def useToken(self):
        self.actionTokens-=1
        self.save()
    
    def startOver(self):
        self.name = "My New School"
        self.year = 1
        self.money = 500000
        self.tuiton = 50000
        Subject.objects.filter(school_id=self.id).delete()
        self.save()

    # creating requires > 0 tokens and > 0 current funds
    def canCreate(self):
        return self.actionTokens > 0 and self.money > 0


class Subject(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=60)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['school', 'name'], name='unique subject')
        ]

    def __str__(self):
        return (
                f"{self.name}"
        )

class Teacher(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE, blank=True, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, blank=True, null=True)
    salary = models.IntegerField(validators=[MinValueValidator(1000), MaxValueValidator(999999)], blank=True, null=True)

    SKILL = [
        (1, 'Lecturer'),
        (2, 'Senior Lecturer'),
        (3, 'Assistant Professor'),
        (4, 'Associate Professor'),
        (5, 'Professor'),
    ]

    skill = models.IntegerField(choices=SKILL, default=1, blank=False, null=True)

    def __str__(self):
        return (
                f"{self.first_name+' '+self.last_name}"
        )
    
    def train(self):
        if self.skill == 5:
            return
        self.skill+=1
        self.updateSalary()
        self.save()
    
    def updateSalary(self):
        if self.skill == 1:
            self.salary = 30000
        elif self.skill == 2:
            self.salary = 40000
        elif self.skill == 3:
            self.salary = 60000
        elif self.skill == 4:
            self.salary = 80000
        else:
            self.salary = 100000

# when a new teacher is created update their salary
@receiver(post_save, sender=Teacher)
def NewTeacher(sender, instance, created, **kwargs):
    if created:
        teacher = instance
        teacher.updateSalary()
        teacher.save()
    
class Student(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE, blank=True, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    major = models.ForeignKey(Subject, on_delete=models.CASCADE, blank=True, null=True)
    year = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(4)], blank=True, null=True, default=1)
    average_grade = models.FloatField(validators=[MinValueValidator(0), MaxValueValidator(100)], default='70')

    def __str__(self):
        return (
                f"{self.first_name+' '+self.last_name}"
        )
    
    def changeGrade(self, factor):
        self.average_grade+=(1.50*factor)
        self.save()
    
    def progressYear(self):
        if self.year == 4:
            self.delete()
        else:
            self.year+=1
            self.save()
    
    def getYear(self):
        if self.year == 1:
            return 'Freshman'
        elif self.year == 2:
            return 'Sophomore'
        elif self.year == 3:
            return 'Junior'
        else:
            return 'Senior'
    
    def getLetterGrade(self):
        if self.average_grade >= 90:
            return 'A'
        elif self.average_grade >= 80:
            return 'B'
        elif self.average_grade >= 70:
            return 'C'
        elif self.average_grade >= 60:
            return 'D'
        else:
            return 'F'

class Class(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=60)
    building = models.ForeignKey(Subject, on_delete=models.CASCADE, blank=True, null=True)
    room = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(1000)], blank=False, null=True)
    teacher = models.ForeignKey(Teacher, related_name="taught_by", on_delete=models.SET_NULL, blank=True, null=True)
    students = models.ManyToManyField(Student, related_name="taken_by", blank=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['school', 'name'], name='unique class')
        ]
    def __str__(self):
        return (
                f"{self.name}"
        )

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SubjectForm, ClassForm, StudentForm, TeacherForm, LoginForm, SignUpForm
from .models import School, Subject, Class, Student, Teacher
from django.db.models import F, Value, Func, CharField
from django.db.models.functions import Concat
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .gameFunctions import computeAvgSalary, computeAvgSkill, computeAvgGradeDist, computeFinancials

# Create your views here.

def home(request):
    school = get_object_or_404(School, id=request.user.id)
    subjects = Subject.objects.filter(school_id=school.id)
    classes = Class.objects.filter(school_id=school.id)
    teachers = Teacher.objects.filter(school_id=school.id)
    students = Student.objects.filter(school_id=school.id)
    subjectForm = SubjectForm()

    # compute school financial information for menubar
    costs = computeFinancials(school)
    
    if request.method == 'POST':
            # if post request sent, store values in subject form
            subjectForm = SubjectForm(request.POST)
            if subjectForm.is_valid():
                subject = subjectForm.save(commit=False)
                # assign subject's user to current user
                subject.school = school
                subject.save()
                messages.success(request, "Building successfully created!")
                return redirect('main:home')
            messages.error(request, "An error has occured, please try again!")
            return redirect('main:home')

    return render(request, "main/home.html", {
        'school': school,
        'subjects': subjects,
        'classes': classes,
        'teachers': teachers,
        'students': students,
        'subjectForm': subjectForm,
        'costs': costs,
    })

@login_required(login_url="main:login_view")
def search(request):
    school = get_object_or_404(School, id=request.user.id)

    # school financial information for user's school
    costs = computeFinancials(school)

    # store user's get request query in q if valid
    q = request.GET.get('q') if bool(request.GET.get('q', False)) else None
    if q is not None:
            # find at most 15 possible queries matching some part of q
            subjects = Subject.objects.filter(school_id=school.id, name__icontains=q)[0:15]
            classes = Class.objects.filter(school_id=school.id, name__icontains=q)[0:15]
            # search full names of teachers and students by concatenating their first and
            # last name fields together in a new virtual field
            teacher_query = Teacher.objects.filter(school_id=school.id).annotate(
                full_name=Concat('first_name', Value(' '), 'last_name', output_field=CharField())
                )
            student_query = Student.objects.filter(school_id=school.id).annotate(
                full_name=Concat('first_name', Value(' '), 'last_name', output_field=CharField())
                )
            # query against new full_name field
            teachers = (teacher_query.filter(full_name__icontains=q))[0:15]
            students = (student_query.filter(full_name__icontains=q))[0:15]
    else:
        messages.error(request, "Invalid search entry. Please try again!")
        return redirect(request.META.get('HTTP_REFERER', '/'))

    return render(request, "main/search.html", {
        'school': school,
        'subjects': subjects,
        'classes': classes,
        'teachers': teachers,
        'students': students,
        'costs': costs,
    })

@login_required(login_url="main:login_view")
def settings(request):
    school = get_object_or_404(School, id=request.user.id)
    schoolForm = SignUpForm(instance=school)

    # financial info for user's school
    costs = computeFinancials(school)

    if request.method == 'POST':
            # if post request used on this page, store values in school form
            schoolForm = SignUpForm(instance=school, data=request.POST)
            if schoolForm.is_valid:
                schoolForm.save()
                messages.success(request, "School successfully edited!")
                return redirect('main:home')
            messages.error(request, "An error has occured, please try again!")
            return redirect('main:settings')

    return render(request, "main/settings.html", {
        'school': school,
        'schoolForm': schoolForm,
        'costs': costs,
    })

def login_view(request):
    form = LoginForm()

    if request.method == 'POST':
        # store values from post request to login form
        form = LoginForm(request.POST)
        if form.is_valid():
            # get username and password values from login form
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            # attempt to authenticate user
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Logged in successfully!')
                return redirect('main:settings')
            else:
                messages.error(request, 'Error logging in. Please try again.')
                return redirect('main:login_view')

    return render(request, "main/login.html", {
        'form': form,
    })

def register_view(request):
    form = SignUpForm()

    if request.method == 'POST':
        # if post request used on this page store values in UCF
        form = SignUpForm(request.POST)
        if form.is_valid():
            # save before authenticating
            form.save()
            # get username and password values from login form
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            # authenticate
            user = authenticate(request, username=username, password=password)
            login(request, user)
            messages.success(request, 'Logged in successfully!')
            return redirect('main:settings')

    return render(request, "main/register.html", {
        'form': form,
    })

def logout_view(request):
    if request.user.is_authenticated:
        # logout user
        logout(request)
        messages.success(request, 'Logged out successfully.')
    return redirect('main:login_view')


@login_required(login_url="main:login_view")
def delete(request, pk, option):
    school = get_object_or_404(School, id=request.user.id)
    # delete path for all user's school objects; determine specific object to delete
    # by checking arguments
    if option == 'subject':
        subject = get_object_or_404(Subject, id=pk)
        subject.delete()
        messages.success(request, "Subject successfully deleted!")
    elif option == 'class':
        user_class = get_object_or_404(Class, id=pk)
        user_class.delete()
        messages.success(request, "Class successfully deleted!")
    elif option == 'teacher':
        teacher = get_object_or_404(Teacher, id=pk)
        teacher.delete()
        messages.success(request, "Teacher successfully deleted!")
    elif option == 'student':
        student = get_object_or_404(Student, id=pk)
        student.delete()
        messages.success(request, "Student successfully deleted!")
    elif option == 'school':
        school = get_object_or_404(School, id=pk)
        school.startOver()
    return redirect('main:home')

@login_required(login_url="main:login_view")
def building(request, pk):
    school = get_object_or_404(School, id=request.user.id)
    subjects = Subject.objects.filter(school_id=school.id)
    building = get_object_or_404(Subject, school_id=school.id, id=pk)
    classForm = ClassForm()

    # user's financial info for school
    costs = computeFinancials(school)

    if request.method == 'POST':
        # if post request used on this page, store values in class form
        classForm = ClassForm(request.POST)
        if classForm.is_valid():
                    newClass = classForm.save(commit=False)
                    # assign class' user to current user
                    newClass.school = school
                    # assign class' building to argument building
                    newClass.building = building
                    newClass.save()
                    messages.success(request, "Class creation successful!")

    return render(request, "main/building.html", {
        'school': school,
        'subject': building,
        'subjects': subjects,
        'form': classForm,
        'costs': costs,
    })

@login_required(login_url="main:login_view")
def class_view(request, name):
    school = get_object_or_404(School, id=request.user.id)
    subjects = Subject.objects.filter(school_id=school.id)
    user_class = get_object_or_404(Class, school_id=school.id, name=name)
    students = Student.objects.filter(school_id=school.id)
    teacherForm = TeacherForm()
    studentForm = StudentForm()

    # user's financial info for school
    costs = computeFinancials(school)

    if request.method == 'POST':
        # register student for class button clicked
        if 'register' in request.POST:
            pk = request.POST.get('register', '')
            student = get_object_or_404(Student, school_id=school.id, id=pk)
            user_class.students.add(student)
            messages.success(request, 'Student registered successfully!')
        # deregister student for class button clicked
        elif 'unregister' in request.POST:
            pk = request.POST.get('unregister', '')
            student = get_object_or_404(Student, school_id=school.id, id=pk)
            user_class.students.remove(student)
            messages.success(request, 'Student unregistered successfully!')

main/templates/main/base.html
{% load humanize %}
<!DOCTYPE html>
<html>

<head>
  <meta charset='utf-8' />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
  {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %} {% load static %}
  <script type="text/javascript" src="{% static 'main/scripts.js' %}"></script>
  <link rel="stylesheet" href="{% static 'main/styles.css' %}">
</head>

<body style="background-color: #e3f2fd;">
  <nav class="navbar navbar-expand-lg" style="background-color: #c7dcf8;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'main:home' %}">ClassManager</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if request.user.is_authenticated %}
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'main:all_teachers' %}">Teachers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'main:all_students' %}">Students</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'main:settings' %}">Settings</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'main:logout_view' %}">Logout</a>
          </li>
        </ul>
        <form class="d-flex" role="search" action="{% url 'main:search' %}">
          <input name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search"
            list="findList">
          <datalist id="findList">
            <select id="list">
              {% for subject in subjects %}
              <option value="{{subject}}">{{subject}}</option>
              {% for class in subject.class_set.all %}
              <option value="{{class}}">{{class}}</option>
              {% endfor %}
              {% for teacher in subject.teacher_set.all %}
              <option value="{{teacher}}">{{teacher}}</option>
              {% endfor %}
              {% for student in subject.student_set.all %}
              <option value="{{student}}">{{student}}</option>
              {% endfor %}
              {% endfor %}
            </select>
          </datalist>
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        {% else %}
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'main:login_view' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'main:register_view' %}">Register</a>
          </li>
        </ul>
        {% endif %}
      </div>
    </div>
  </nav>
  <div class="container">
    {% if messages %} {% for message in messages %}
    <div class="alert alert-warning" role="alert">
      {{message}}
    </div>
    {% endfor %}
    <br />
    {% endif %}
    {% if request.user.is_authenticated %}
    <br />
    {% endif %}
    {% block content %}{% endblock %}
  </div>
</body>

</html>

main/templates/main/home.html
{% extends "main/base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
{% load static %}

{% if request.user.is_authenticated %}
<center>
  <h1>Departments</h1>
</center>
<br>
{% include 'main/menubar.html' %}
<br>

<center>
  <div id="subject-container" class="container overflow-hidden text-center">
    <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
      {% for subject in subjects %} {% if subject %}
      <div class="col-2">
        <div id="{{subject.id}}" class="card mb-3" style="max-width: 18rem;">
          <div class="card-header bg-primary">
            <h5><a class="title-header link-dark bg-primary fw-medium"
                href="{% url 'main:building' subject.id %}">{{subject|capfirst}} <i
                  class="bi bi-arrow-up-right-circle"></i></a></h5>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <span style="width: 100%;" class="m-1 badge bg-dark">Classes: <span class="badge bg-secondary"> {{subject.class_set.count}}</span></span>
              <br />
              <span style="width: 100%;" class="m-1 badge bg-dark">Faculty: <span class="badge bg-secondary"> {{subject.teacher_set.count}}</span></span>
              <br />
              <span style="width: 100%;" class="m-1 badge bg-dark">Students: <span class="badge bg-secondary"> {{subject.student_set.count}}</span></span>
            </h5>
            <a href="{% url 'main:delete' subject.id 'subject' %}">
              <button type="button" class="btn btn-outline-danger">Demolish</button>
            </a>
          </div>
        </div>
      </div>
      {% endif %} {% endfor %}
      <div id="start_create_subject" class="col-2">
        <div class="card mb-3" style="max-width: 18rem">
          <div class="card-header bg-primary">
            <h5 class="text-dark bg-primary fw-medium">New Building?</h5>
          </div>
          <div class="card-body">
            <button class="toggler card-title btn btn-outline-primary" id="subject">Build</button>
          </div>
        </div>
      </div>
      <div id="create_subject" class="col-2" style="display: none">
        <div class="card mb-3" style="max-width: 18rem">
          <div class="card-header bg-primary">
            <h5 class="text-dark bg-primary fw-medium">Build Building</h5>
          </div>
          <div class="card-body">
            <div class="card-title">
              <form method="POST" action="">
                {% csrf_token %} {{subjectForm}}
                <br />
                <br>
                <button name="subject_form" class="btn btn-outline-success" type="submit">Submit</button>
                <button class="toggler btn btn-outline-danger" id="subject">Cancel</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</center>
{% endif %}

<script>
  function toggleEditSection(id) {
    let category;
    if ((category = document.getElementById(id)) != null) {
      if (category.style.display == "none") {
        category.style.display = "block";
        document.querySelector("#start_" + id).style.display = "none";
      } else {
        category.style.display = "none";
        document.querySelector("#start_" + id).style.display = "block";
      }
    }
  }

  document.addEventListener("DOMContentLoaded", () => {
    document.querySelectorAll(".toggler").forEach((el) => {
      el.onclick = (el) => {
        toggleEditSection("create_" + el.target.id);
      };
    });
  });
</script>

{% endblock %}

main/templates/main/search.html
{% extends "main/base.html" %}
{% block title %}Search{% endblock %}
{% block content %}
{% load static %}

{% if request.user.is_authenticated %}
<center>
    <h3>Results</h3>
</center>
<br>
{% include 'main/menubar.html' %}
<br>
{% if subjects %}
<h4>Subjects</h4>
<hr>
<div id="subject-container" class="container overflow-hidden text-center">
    <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
        {% for subject in subjects %}
        <div class="col-2">
            <div id="{{subject.id}}" class="card mb-3" style="max-width: 18rem;">
                <div class="card-header bg-primary">
                    <h5><a class="title-header link-dark bg-primary fw-medium"
                            href="{% url 'main:building' subject.id %}">{{subject|capfirst}}</a></h5>
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        <span style="width: 100%;" class="m-1 badge bg-dark">Classes: <span class="badge bg-secondary">
                                {{ subject.class_set.count }}</span></span>
                        <br />
                        <span style="width: 100%;" class="m-1 badge bg-dark">Faculty: <span class="badge bg-secondary">
                                {{ subject.teacher_set.count }}</span></span>
                        <br />
                        <span style="width: 100%;" class="m-1 badge bg-dark">Students: <span class="badge bg-secondary">
                                {{ subject.student_set.count }}</span></span>
                    </h5>
                    <a href="{% url 'main:delete' subject.id 'subject' %}">
                        <button type="button" class="btn btn-outline-danger">Demolish</button>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}
{% if classes %}
<h4>Classes</h4>
<hr>
<div id="class-container" class="container overflow-hidden text-center">
    <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
        {% for class in classes %}
        <div class="col-2">
            <div id="{{class.id}}" class="card mb-3" style="max-width: 18rem;">
                <div class="card-header bg-primary">
                    <h5><a class="title-header link-dark bg-primary fw-medium"
                            href="{% url 'main:class' class.name %}">{{class.name|capfirst}}</a></h5>
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        <span style="width: 100%;" class="m-1 badge bg-dark">Faculty: <span class="badge bg-secondary">
                            {% if class.teacher %}
                                <a class="col-header link-light" href="{% url 'main:teacher' class.teacher.id %}">{{class.teacher}}</a></span></span>
                            {% else %}
                                <a class="col-header link-light">TBA</a></span></span>TBA
                            {% endif %}
                        <br />
                        <span style="width: 100%;" class="m-1 badge bg-dark">Room <span class="badge bg-secondary"> {{class.room }}</span></span>
                        <br />
                        <span style="width: 100%;" class="m-1 badge bg-dark">Students: <span class="badge bg-secondary">
                                {{ class.students.count }}</span></span>
                    </h5>
                    <a href="{% url 'main:delete' class.id 'class' %}">
                        <button type="button" class="btn btn-outline-danger">Remove</button>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}
{% if teachers %}
<h4>Teachers</h4>
<hr>
<div id="teacher-container" class="container overflow-hidden text-center">
    <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
        {% for teacher in teachers %}
        <div class="col-2">
            <div id="{{teacher.id}}" class="card mb-3" style="max-width: 18rem;">
                <div class="card-header bg-primary">
                    <h5><a class="title-header link-dark bg-primary fw-medium"
                            href="{% url 'main:teacher' teacher.id %}">{{teacher|title}}</a></h5>
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        <span style="width: 100%;" class="m-1 badge bg-dark">{{ teacher.get_skill_display }}</span>
                        <br />
                        <span style="width: 100%;" class="m-1 badge bg-dark">Focus: <span
                                class="badge bg-secondary"> {{ teacher.subject }}</span></span>
                        <br />
                        <span style="width: 100%;" class="m-1 badge bg-dark">Salary: <span class="badge bg-secondary">
                                {{ teacher.salary }}</span></span>
                    </h5>
                    {% if school.checkTokens > 0 %}
                    <a class="me-2" href="{% url 'main:train' teacher.id %}"><button type="button"
                            class="btn btn-outline-warning">Train</button></a>
                    {% endif %}
                    <a href="{% url 'main:delete' teacher.id 'teacher' %}">
                        <button type="button" class="btn btn-outline-danger">Fire</button>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}

{% if students %}
<h4>Students</h4>
<hr>
<div id="student-container" class="container overflow-hidden text-center">
    <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
        {% for student in students %}
        <div class="col-2">
            <div id="{{teacher.id}}" class="card mb-3" style="max-width: 18rem;">
                <div class="card-header bg-primary">
                    <h5><a class="title-header link-dark bg-primary fw-medium"
                            href="{% url 'main:student' student.id %}">{{student|title}}</a></h5>
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        <span style="width: 100%;" class="m-1 badge bg-dark">Year: <span class="badge bg-secondary"> {{student.getYear}}</span></span>
                        <br />
                        <span style="width: 100%;" class="m-1 badge bg-dark">Major: <span class="badge bg-secondary"> {{student.major}}</span></span>
                        <br />
                        <span style="width: 100%;" class="m-1 badge bg-dark">Average Grade: <span
                                class="badge bg-secondary"> {{student.getLetterGrade}}</span></span>
                    </h5>
                    <a href="{% url 'main:delete' student.id 'student' %}">
                        <button type="button" class="btn btn-outline-danger">Expel</button>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}
{% endif %}

{% endblock %}